# Generated by Django 4.2.13 on 2024-06-19 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie_management", "0002_remove_movie_director_alter_movie_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=300)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
