# Generated by Django 4.2.13 on 2024-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_management", "0004_alter_director_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="role",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
